<a href="https://colab.research.google.com/github/recervictory/LearingR/blob/main/01_Introducation_to_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introduction to R


In [ ]:
# In "R" The hashtag is used to add comments
# Calculate 4+6
4+6

In [ ]:
# What can we do with R
demo("graphics")

## 1.1 Arithmetic with R
R use **arithmetic operators** to calculate various arithmetic function
- Addition: +
- Subtraction: -
- Multiplication: *
- Division: /
- Exponentiation: ^
- Modulo: %%


In [ ]:
# An addition
15 + 5

# A substraction
50 - 5

# A multiplication
4 * 5

# A division
(5 + 5)/2

# Exponentiation
2^5
# Modulo
17%%4

## 1.2 Variable assignment
A basic concept in (statistical) programming is called a variable. A variable allows you to store a value (e.g. 4) or an object (e.g. a function description) in R. 
Assigning Variable in R:

`my_var <- 15`

`num <- 4`


In [ ]:
 pi <- 3.14
 pi

In [ ]:
pi <- 3.141592653589793238462
phi <- 1.61803399
hi <- pi * phi
hi

## 1.3 Basic data types in R
R works with numerous data types. Some of the most basic types to get started are:

- Decimal values like 4.5 are called **numerics**.
- Whole numbers like 4 are called **integers**. Integers are also **numerics**.
- Boolean values (TRUE or FALSE) are called **logical**.
- Text (or string) values are called **characters**. For string data type we need `quotation marks` to indicate is string.

In [ ]:
num <- 4.5
my_int <- 56
my_logical <- TRUE
my_name <- "R Code"
my_name
my_logical

**To check the data type of of a variable we use** `class()` **fuction**

In [ ]:
class(my_logical)
class(my_name)
class(my_int)
class(num)

# 2. Working with Vectors



<h2 align=center>Example of Dataset</h2>

This is a common example of datasets table used for data analysis.This table has one row for each movie and several columns.

-   **name** - The name of the movie
-   **year** - The year the movie was released
-   **length_min** - The lenght of the movie in minutes
-   **genre** - The genre of the movie
-   **average_rating** - Average rating on Imdb
-   **cost_millions** - The movie's production cost in millions
-   **sequences** - The amount of sequences
-   **foreign** - Indicative of whether the movie is foreign (1) or domestic (0)
-   **age_restriction** - The age restriction for the movie
    <br>
    <br>

Here's what the data looks like:

<img src = "https://ibm.box.com/shared/static/6kr8sg0n6pc40zd1xn6hjhtvy3k7cmeq.png" width = 90% align="left">


**Vectors** are **one-dimension arrays** that can hold numeric data, character data, or logical data. In other words, a vector is a simple tool to store data. 
In R, you create a vector with the **combine function** `c()`. You place the vector elements separated by a comma between the parentheses. For example:
```
numeric_vector <- c(1, 2, 3)
character_vector <- c("a", "b", "c")
```

In [ ]:
numeric_vector <- c(1, 10, 49)
character_vector <- c("a", "b", "c")
logical_vector <- c(TRUE, FALSE,FALSE)
# print vectors
numeric_vector
character_vector
logical_vector

In [ ]:
# datatypes of vectors
class(numeric_vector)
class(logical_vector)

## 2.1 Naming a vector
With vectors, you can give **names to the elements** of a vector using the `names()` function:

In [ ]:
#Creating a year vector
release_year <- c(1985, 1999, 2010, 2002)
release_year

#Assigning names
names(release_year) <- c("The Breakfast Club", "American Beauty", "Black Swan", "Chicago")
release_year

In [ ]:
# Now, you can retrieve the values based on the names:
release_year[c("American Beauty", "Chicago")]

In [ ]:
names(release_year)

## 2.2 Vector Operations


In [ ]:
release_year <- c(1985, 1999, 2015, 1964)
release_year
# Adding more elements to a vector
release_year <- c(release_year, 2016:2020)
release_year

In [ ]:
# Length of a vector
length(release_year)

In [ ]:
# Head and Tail of a vector
head(release_year) #first six items
tail(release_year) #last six items

In [ ]:
# Sorting a vector
sort(release_year)

In [ ]:
sort(release_year, decreasing = T)

In [ ]:
# minimum and maximum values of a vector, you can use the **`min()`** and **`max()`** functions
min(release_year)
max(release_year)

In [ ]:
# Simple Stat Vectors
cost <- c(12.8,11,8.6,9.3,14.2,10.9)
mean(cost)
median(cost)
sum(cost)
# Summary of Vectors
summary(cost)

## 3.3 Vector Selection

In [13]:
shop1 <- c(140, -50, 20, -120, 240)
shop2 <- c(-24, -50, 100, -350, 10)
days <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
names(shop1) <- days
names(shop2) <- days
shop1[1] # one based index
shop2[2]
shop1['Friday']
shop2[c("Monday","Tuesday")]

Monday 
   140

Tuesday 
    -50

Friday 
   240

Monday Tuesday 
    -24     -50

In [12]:
shop1[c(2,3,4)]
shop2[c(2:4)]

Tuesday Wednesday  Thursday 
      -50        20      -120

Tuesday Wednesday  Thursday 
      -50       100      -350

### Selection by comparison 
By making use of comparison operators, 
The (logical) comparison operators known to R are:
- `<` for less than
- `>` for greater than
- `<=` for less than or equal to
- `>=` for greater than or equal to
- `==` for equal to each other
- `!=` not equal to each other


In [14]:
# logical comparison
profit <- shop1 > 0
profit

Monday   Tuesday Wednesday  Thursday    Friday 
     TRUE     FALSE      TRUE     FALSE      TRUE

In [15]:
# subseting
shop1[profit]

Monday Wednesday    Friday 
      140        20       240

# 3. Working with Matrix
**In R, a matrix is a collection of elements of the same data type (numeric, character, or logical) arranged into a fixed number of rows and columns.**
You can construct a matrix in R with the `matrix()` function. Consider the following example:

`matrix(1:12, byrow = TRUE, nrow = 3)`
- The first argument is the collection of elements that R will arrange into the rows and columns of the matrix. Here, we use 1:12 which is a shortcut for c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12).
- The argument **byrow** indicates that the matrix is filled by the rows. If we want the matrix to be filled by the columns, we just place byrow = FALSE.
- The third argument nrow indicates that the matrix should have three rows.

In [20]:
# Construct a matrix with 3 rows that contain the numbers 1 up to 9
matrix(1:12,byrow=TRUE,nrow =4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [22]:
# Using Vectors to construct matrix
toy_story <- c(1995,81,8.3)
akira <- c(1998,125,8.1)
room <- c(2015,118,8.3)

movies <- c(toy_story,akira,room)
movies_matrix <- matrix(movies,byrow = TRUE,nrow = 3)
movies_matrix

[,1] [,2] [,3]
[1,] 1995  81  8.3 
[2,] 1998 125  8.1 
[3,] 2015 118  8.3

## 3.1 Naming a matrix
Similar to vectors, you can add names for the rows and the columns of a matrix
```
rownames(my_matrix) <- row_names_vector
colnames(my_matrix) <- col_names_vector
```


In [25]:
rownames(movies_matrix) <- c('toy_story','akira','room')
colnames(movies_matrix) <- c('year','length_min','rating')
movies_matrix

year length_min rating
toy_story 1995  81        8.3   
akira     1998 125        8.1   
room      2015 118        8.3

## 3.2 Adding Rows and Columns to Matrix
- `cbind()` function merges matrices and/or vectors together by column. For example: `big_matrix <- cbind(matrix1, matrix2, vector1 ...)`
- `rbind()` function erges matrices and/or vectors together by row For example: `big_matrix <- rbind(matrix1, matrix2, vector1 ...)`

In [26]:
cost <- c(30,10.4,13)
movies_matrix <- cbind(movies_matrix, cost)

In [27]:
movies_matrix

year length_min rating cost
toy_story 1995  81        8.3    30.0
akira     1998 125        8.1    10.4
room      2015 118        8.3    13.0

In [28]:
casino <- c(1995,178,8.2,50)
movies_matrix <- rbind(movies_matrix,casino)

In [29]:
movies_matrix

year length_min rating cost
toy_story 1995  81        8.3    30.0
akira     1998 125        8.1    10.4
room      2015 118        8.3    13.0
casino    1995 178        8.2    50.0

## 3.3 Selection of matrix elements
Similar to vectors, you can use the square brackets `[ ]` to select one or multiple elements from a matrix. Whereas vectors have one dimension, matrices have two dimensions. You should therefore use a comma to separate the rows you want to select from the columns. For example:
- `my_matrix[col,row]`
- `my_matrix[1,2]` selects the element at the first row and second column.
- `my_matrix[1:3,2:4]` results in a matrix with the data on the rows 1, 2, 3 and columns 2, 3, 4.

In [37]:
movies_matrix

year length_min rating cost
toy_story 1995  81        8.3    30.0
akira     1998 125        8.1    10.4
room      2015 118        8.3    13.0
casino    1995 178        8.2    50.0

In [35]:
movies_matrix[2:3,1:4]

year length_min rating cost
akira 1998 125        8.1    10.4
room  2015 118        8.3    13.0

In [41]:
movies_matrix[,1]

toy_story     akira      room    casino 
     1995      1998      2015      1995

In [42]:
movies_matrix[1,]

year length_min     rating       cost 
    1995.0       81.0        8.3       30.0

## 3.4 Arithmetic with matrices
Similar to what you have learned with vectors, the standard operators like `+, -, /, *,` etc. work in an element-wise way on matrices in R.

- For example, `2 * my_matrix` multiplies each element of my_matrix by two.

In [43]:
matrix1 <- matrix(1:12,byrow=TRUE,nrow =4)
matrix1

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [49]:
matrix2 <- matrix1 /5
matrix2

[,1] [,2] [,3]
[1,] 0.2  0.4  0.6 
[2,] 0.8  1.0  1.2 
[3,] 1.4  1.6  1.8 
[4,] 2.0  2.2  2.4

In [50]:
matrix1 + matrix2

[,1] [,2] [,3]
[1,]  1.2  2.4  3.6
[2,]  4.8  6.0  7.2
[3,]  8.4  9.6 10.8
[4,] 12.0 13.2 14.4

In [51]:
matrix1 * matrix2

[,1] [,2] [,3]
[1,]  0.2  0.8  1.8
[2,]  3.2  5.0  7.2
[3,]  9.8 12.8 16.2
[4,] 20.0 24.2 28.8

# 4. Working with Factor
The term factor refers to a **statistical data type** used to store **categorical variables**. The difference between a categorical variable and a continuous variable is that a **categorical variable** can belong to a **limited number of categories**. A continuous variable, on the other hand, can correspond to an **infinite number of values**.
- A good example of a categorical variable is sex. In many circumstances you can limit the sex categories to "Male" or "Female".