<a href="https://colab.research.google.com/github/recervictory/LearingR/blob/main/01_Introducation_to_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0. R
## What is R ?
R refers to two things.There is R, the **programming language**, and
R, the piece of software that you use to **run programs written in R**.

## Why R ?
- R is a free, open source language for data analysis.
- It’s also a piece of software used to run programs written in R.
- You can download R from http://www.r-project.org.
- You can write R code in any text editor, but there are several IDEs that make development easier.

# RUNNING AN R KERNEL IN GOOGLE COLAB
https://colab.research.google.com/notebook#create=true&language=r




In [1]:
 # GET TO KNOW THE R VERSION
 R.version

               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out     

In [3]:
# INSTALL PACKAGES
install.packages('dtplyr')

# Import Library
library(dtplyr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



# 1. Introduction to R
Three main data types in R
- **Vectors (one dimensional array)**: can hold numeric, character or logical values. The elements in a vector all have the same data type.
- **Matrices (two dimensional array)**: can hold numeric, character or logical values. The elements in a matrix all have the same data type.
- **Data frames (two-dimensional objects)**: can hold numeric, character or logical values. Within a column all elements have the same data type, but different columns can be of different data type.


In [ ]:
# In "R" The hashtag is used to add comments
# Calculate 4+6
4+6

In [ ]:
# What can we do with R
demo("graphics")

## 1.1 Arithmetic with R
R use **arithmetic operators** to calculate various arithmetic function
- Addition: +
- Subtraction: -
- Multiplication: *
- Division: /
- Exponentiation: ^
- Modulo: %%


In [ ]:
# An addition
15 + 5

# A substraction
50 - 5

# A multiplication
4 * 5

# A division
(5 + 5)/2

# Exponentiation
2^5

# Modulo
17%%4

## 1.2 Variable assignment
A basic concept in (statistical) programming is called a variable. A variable allows you to store a value (e.g. 4) or an object (e.g. a function description) in R. 
Assigning Variable in R:

`my_var <- 15`

`num <- 4`


In [ ]:
 pi <- 3.14
 pi

In [ ]:
pi <- 3.141592653589793238462
phi <- 1.61803399
hi <- pi * phi
hi

## 1.3 Basic data types in R
R works with numerous data types. Some of the most basic types to get started are:

- Decimal values like 4.5 are called **numerics**.
- Whole numbers like 4 are called **integers**. Integers are also **numerics**.
- Boolean values (TRUE or FALSE) are called **logical**.
- Text (or string) values are called **characters**. For string data type we need `quotation marks` to indicate is string.

In [ ]:
num <- 4.5
my_int <- 56
my_logical <- TRUE
my_name <- "R Code"
my_name
my_logical

**To check the data type of of a variable we use** `class()` **fuction**

In [ ]:
class(my_logical)
class(my_name)
class(my_int)
class(num)

# 2. Working with Vectors



<h2 align=center>Example of Dataset</h2>

This is a common example of datasets table used for data analysis.This table has one row for each movie and several columns.

-   **name** - The name of the movie
-   **year** - The year the movie was released
-   **length_min** - The lenght of the movie in minutes
-   **genre** - The genre of the movie
-   **average_rating** - Average rating on Imdb
-   **cost_millions** - The movie's production cost in millions
-   **sequences** - The amount of sequences
-   **foreign** - Indicative of whether the movie is foreign (1) or domestic (0)
-   **age_restriction** - The age restriction for the movie
    <br>
    <br>

Here's what the data looks like:

<img src = "https://ibm.box.com/shared/static/6kr8sg0n6pc40zd1xn6hjhtvy3k7cmeq.png" width = 90% align="left">


**Vectors** are **one-dimension arrays** that can hold numeric data, character data, or logical data. In other words, a vector is a simple tool to store data. 
In R, you create a vector with the **combine function** `c()`. You place the vector elements separated by a comma between the parentheses. For example:
```
numeric_vector <- c(1, 2, 3)
character_vector <- c("a", "b", "c")
```

In [ ]:
numeric_vector <- c(1, 10, 49)
character_vector <- c("a", "b", "c")
logical_vector <- c(TRUE, FALSE,FALSE)
# print vectors
numeric_vector
character_vector
logical_vector

In [ ]:
# datatypes of vectors
class(numeric_vector)
class(logical_vector)

In [24]:
# Creating Some Empty Vetors
vector("numeric", 5)
vector("logical", 5)
vector("character", 5)

[1] 0 0 0 0 0

[1] FALSE FALSE FALSE FALSE FALSE

[1] "" "" "" "" ""

## 2.1 Naming a vector
With vectors, you can give **names to the elements** of a vector using the `names()` function:

In [25]:
#Creating a year vector
release_year <- c(1985, 1999, 2010, 2002)
release_year

[1] 1985 1999 2010 2002

In [8]:
#Assigning names
names(release_year) <- c("The Breakfast Club", "American Beauty", "Black Swan", "Chicago")
release_year

The Breakfast Club    American Beauty         Black Swan            Chicago 
              1985               1999               2010               2002

In [9]:
# Now, you can retrieve the values based on the names:
release_year[c("American Beauty", "Chicago")]

American Beauty         Chicago 
           1999            2002

In [10]:
names(release_year)

[1] "The Breakfast Club" "American Beauty"    "Black Swan"        
[4] "Chicago"

## 2.2 Vector Operations


In [11]:
release_year <- c(1985, 1999, 2015, 1964)
release_year
# Adding more elements to a vector
release_year <- c(release_year, 2016:2020)
release_year

[1] 1985 1999 2015 1964

[1] 1985 1999 2015 1964 2016 2017 2018 2019 2020

In [12]:
# Length of a vector
length(release_year)

[1] 9

In [13]:
# Head and Tail of a vector
head(release_year) #first six items
tail(release_year) #last six items

[1] 1985 1999 2015 1964 2016 2017

[1] 1964 2016 2017 2018 2019 2020

In [14]:
# Sorting a vector
sort(release_year)

[1] 1964 1985 1999 2015 2016 2017 2018 2019 2020

In [15]:
sort(release_year, decreasing = T)

[1] 2020 2019 2018 2017 2016 2015 1999 1985 1964

In [16]:
# minimum and maximum values of a vector, you can use the **`min()`** and **`max()`** functions
min(release_year)
max(release_year)

[1] 1964

[1] 2020

In [17]:
# Simple Stat Vectors
cost <- c(12.8,11,8.6,9.3,14.2,10.9)
mean(cost)
median(cost)
sum(cost)
# Summary of Vectors
summary(cost)

[1] 11.13333

[1] 10.95

[1] 66.8

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   8.60    9.70   10.95   11.13   12.35   14.20 

## 3.3 Vector Selection
**Impotant: R use one as Staring index.**

In [20]:
# Assigning Two Variables shop with respective sells
shop1 <- c(140, -50, 20, -120, 240)
shop2 <- c(-24, -50, 100, -350, 10)

# Creating Name Varibale
days <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

#Assigning Names
names(shop1) <- days
names(shop2) <- days

# Index Based selection
shop1[1] # one based index
shop2[2] 

# Name Based Selection
shop1['Friday']
shop2[c("Monday","Tuesday")]

Monday 
   140

Tuesday 
    -50

Friday 
   240

Monday Tuesday 
    -24     -50

In [21]:
# Selection using combine function c()
shop1[c(2,3,4)]
shop2[c(2:4)]

Tuesday Wednesday  Thursday 
      -50        20      -120

Tuesday Wednesday  Thursday 
      -50       100      -350

### Selection by comparison 
By making use of comparison operators, 
The (logical) comparison operators known to R are:
- `<` for less than
- `>` for greater than
- `<=` for less than or equal to
- `>=` for greater than or equal to
- `==` for equal to each other
- `!=` not equal to each other


In [22]:
# logical comparison
profit <- shop1 > 0
profit

Monday   Tuesday Wednesday  Thursday    Friday 
     TRUE     FALSE      TRUE     FALSE      TRUE

In [23]:
# subseting
shop1[profit]

Monday Wednesday    Friday 
      140        20       240

# 3. Working with Matrix
**In R, a matrix is a collection of elements of the same data type (numeric, character, or logical) arranged into a fixed number of rows and columns.**
You can construct a matrix in R with the `matrix()` function. Consider the following example:

`matrix(1:12, byrow = TRUE, nrow = 3)`
- The first argument is the collection of elements that R will arrange into the rows and columns of the matrix. Here, we use 1:12 which is a shortcut for c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12).
- The argument **byrow** indicates that the matrix is filled by the rows. If we want the matrix to be filled by the columns, we just place byrow = FALSE.
- The third argument nrow indicates that the matrix should have three rows.

In [35]:
# Construct a matrix with 3 rows that contain the numbers 1 up to 9
matrix(1:12,byrow=TRUE,nrow =4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [34]:
# Using Vectors to construct matrix

# Creating Vectors
toy_story <- c(1995,81,8.3)
akira <- c(1998,125,8.1)
room <- c(2015,118,8.3)

# Creating Matrix
movies <- c(toy_story,akira,room)
movies_matrix <- matrix(movies,byrow = TRUE,nrow = 3)
movies_matrix

[,1] [,2] [,3]
[1,] 1995  81  8.3 
[2,] 1998 125  8.1 
[3,] 2015 118  8.3

## 3.1 Naming a matrix
Similar to vectors, you can add names for the rows and the columns of a matrix
```
rownames(my_matrix) <- row_names_vector
colnames(my_matrix) <- col_names_vector
```


In [36]:
rownames(movies_matrix) <- c('toy_story','akira','room')
colnames(movies_matrix) <- c('year','length_min','rating')
movies_matrix

year length_min rating
toy_story 1995  81        8.3   
akira     1998 125        8.1   
room      2015 118        8.3

## 3.2 Adding Rows and Columns to Matrix
- `cbind()` function merges matrices and/or vectors together by column. For example: `big_matrix <- cbind(matrix1, matrix2, vector1 ...)`
- `rbind()` function merges matrices and/or vectors together by row For example: `big_matrix <- rbind(matrix1, matrix2, vector1 ...)`

In [37]:
# Merging vector as a Column
cost <- c(30,10.4,13)
movies_matrix <- cbind(movies_matrix, cost)

In [38]:
movies_matrix

year length_min rating cost
toy_story 1995  81        8.3    30.0
akira     1998 125        8.1    10.4
room      2015 118        8.3    13.0

In [39]:
# Maring new Row from vector
casino <- c(1995,178,8.2,50)
movies_matrix <- rbind(movies_matrix,casino)

In [40]:
movies_matrix

year length_min rating cost
toy_story 1995  81        8.3    30.0
akira     1998 125        8.1    10.4
room      2015 118        8.3    13.0
casino    1995 178        8.2    50.0

## 3.3 Selection of matrix elements
Similar to vectors, you can use the square brackets `[ ]` to select one or multiple elements from a matrix. Whereas vectors have one dimension, matrices have two dimensions. You should therefore use a comma to separate the rows you want to select from the columns. For example:
- `my_matrix[row,col]`
- `my_matrix[1,2]` selects the element at the first row and second column.
- `my_matrix[1:3,2:4]` results in a matrix with the data on the rows 1, 2, 3 and columns 2, 3, 4.

In [41]:
movies_matrix

year length_min rating cost
toy_story 1995  81        8.3    30.0
akira     1998 125        8.1    10.4
room      2015 118        8.3    13.0
casino    1995 178        8.2    50.0

In [42]:
movies_matrix[2:3,1:4]

year length_min rating cost
akira 1998 125        8.1    10.4
room  2015 118        8.3    13.0

In [43]:
movies_matrix[,1] # selects all elements of the first column.

toy_story     akira      room    casino 
     1995      1998      2015      1995

In [44]:
movies_matrix[1,] # selects all elements of the first row.

year length_min     rating       cost 
    1995.0       81.0        8.3       30.0

## 3.4 Arithmetic with matrices
Similar to what you have learned with vectors, the standard operators like `+, -, /, *,` etc. work in an element-wise way on matrices in R.

- For example, `2 * my_matrix` multiplies each element of my_matrix by two.

In [45]:
matrix1 <- matrix(1:12,byrow=TRUE,nrow =4)
matrix1

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [46]:
matrix2 <- matrix1 /5
matrix2

[,1] [,2] [,3]
[1,] 0.2  0.4  0.6 
[2,] 0.8  1.0  1.2 
[3,] 1.4  1.6  1.8 
[4,] 2.0  2.2  2.4

In [47]:
matrix1 + matrix2

[,1] [,2] [,3]
[1,]  1.2  2.4  3.6
[2,]  4.8  6.0  7.2
[3,]  8.4  9.6 10.8
[4,] 12.0 13.2 14.4

In [48]:
matrix1 * matrix2

[,1] [,2] [,3]
[1,]  0.2  0.8  1.8
[2,]  3.2  5.0  7.2
[3,]  9.8 12.8 16.2
[4,] 20.0 24.2 28.8

# 4. Working with Factor
The term factor refers to a **statistical data type** used to store **categorical variables**. The difference between a categorical variable and a continuous variable is that a **categorical variable** can belong to a **limited number of categories**. A continuous variable, on the other hand, can correspond to an **infinite number of values**.
- A good example of a categorical variable is sex. In many circumstances you can limit the sex categories to "Male" or "Female".

To create factors in R, you make use of the function `factor()`. 
It is clear that there are two categories, or in R-terms 'factor levels', at work here: "Male" and "Female".

In [49]:
# Gender vector
gender_vector <- c("Male", "Female", "Female", "Male", "Male")

# Convert gender_vector to a factor
factor_gender_vector <-factor(gender_vector)
  
# Print out factor_gender_vector
factor_gender_vector 

[1] Male   Female Female Male   Male  
Levels: Female Male

 ### 4.1 Types of Categorical Variable
 There are two types of categorical variables: 
 
 - **Nominal categorical variable** 
 - **Ordinal categorical variable**.
 
- A nominal variable is a categorical variable without an **implied order**. This means that it is impossible to say that **'one is worth more than the other'**. For example, think of the categorical variable animals_vector with the categories "Elephant", "Giraffe", "Donkey" and "Horse". 
- In contrast, ordinal variables do have a **natural ordering**. Consider for example the categorical variable temperature_vector with the categories: "Low", "Medium" and "High". Here it is obvious that "Medium" stands above "Low", and "High" stands above "Medium".

In [50]:
# Animals
animals_vector <- c("Elephant", "Giraffe", "Donkey", "Horse")
factor_animals_vector <- factor(animals_vector)
factor_animals_vector

# Temperature
temperature_vector <- c("High", "Low", "High","Low", "Medium")
factor_temperature_vector <- factor(temperature_vector, order = FALSE, levels = c("Low", "Medium", "High"))
factor_temperature_vector

[1] Elephant Giraffe  Donkey   Horse   
Levels: Donkey Elephant Giraffe Horse

[1] High   Low    High   Low    Medium
Levels: Low Medium High

## 4.2 Changing the Factors Value
You will often want to change the factor levels to "Male" and "Female" instead of "M" and "F" for clarity.  R allows you to do this with the function `levels()`:
> levels(factor_vector) <- c("name1", "name2",...)

In [51]:
# Code to build factor_survey_vector
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector
# Specify the levels of factor_survey_vector
levels(factor_survey_vector) <- c("Female","Male")

factor_survey_vector

[1] M F F M M
Levels: F M

[1] Male   Female Female Male   Male  
Levels: Female Male

In [52]:
survey_vector

[1] "M" "F" "F" "M" "M"

## 4.3 Summarizing a factor:
The `summary()` will will give you a quick overview of the contents of a variable:
> summary(my_var)

In [53]:
# Build factor_survey_vector with clean levels
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
levels(factor_survey_vector) <- c("Female", "Male")
factor_survey_vector

[1] Male   Female Female Male   Male  
Levels: Female Male

In [54]:
# Generate summary for survey_vector
summary(survey_vector)

   Length     Class      Mode 
        5 character character 

In [55]:
# Generate summary for factor_survey_vector
summary(factor_survey_vector)

Female   Male 
     2      3

## 4.4 Ordered factors
Sometimes we need to work with the **ordered categorical** data like ("slow", "medium", "fast"). In that case a categorical data needed to convert to ordinal form.  By default, the function `factor()` transforms speed_vector into an unordered factor. To create an ordered factor, you have to add two additional arguments: `ordered` and `levels`.

> factor(some_vector,ordered = TRUE, levels = c("lev1", "lev2" ...))


In [56]:
# Create speed_vector
speed_vector <- c("fast", "slow", "slow", "fast", "medium") 

# Convert speed_vector to ordered factor vector
factor_speed_vector <- factor(speed_vector,ordered=TRUE,levels=c("slow", "medium", "fast")) 

# Print factor_speed_vector
factor_speed_vector
summary(factor_speed_vector)

[1] fast   slow   slow   fast   medium
Levels: slow < medium < fast

slow medium   fast 
     2      1      2

# 5. Working with Dataframe

In [57]:
# Print out built-in R data frame
mtcars 

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3   
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3   
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4   
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4   
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2   
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2   
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4   
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2   
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4   
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6   
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8   
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

### 5.1 Head and Tail function
The function head() enables you to show the first observations of a data frame. Similarly, the function tail() prints out the last observations in your data set.

In [58]:
# Call head() on mtcars
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [59]:
# Call tail() on mtcars
tail(mtcars)

mpg  cyl disp  hp  drat wt    qsec vs am gear carb
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.7 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.9 1  1  5    2   
Ford Pantera L 15.8 8   351.0 264 4.22 3.170 14.5 0  1  5    4   
Ferrari Dino   19.7 6   145.0 175 3.62 2.770 15.5 0  1  5    6   
Maserati Bora  15.0 8   301.0 335 3.54 3.570 14.6 0  1  5    8   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.6 1  1  4    2

### 5.2 Dataframe structure
Another method that is often used to get a rapid overview of your data is the function `str()`. The function `str()` shows you the structure of your data set. For a data frame it tells you:

- The total number of observations (e.g. 32 car types)
- The total number of variables (e.g. 11 car features)
- A full list of the variables names (e.g. mpg, cyl … )
- The data type of each variable (e.g. num)

**The first observations**
Applying the `str()` function will often be the first thing that you do when receiving a new data set or data frame. It is a great way to get more insight in your data set before diving into the real analysis

In [60]:
# Investigate the structure of mtcars
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


In [61]:
# Investigate the structure of iris
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


### 5.3: Creating a data frame
We construct a data frame with the `data.frame()` function. As arguments, you pass the vectors from before: they will become the different columns of your data frame. Because every column has the same length, the vectors you pass should also have the same length. But don't forget that it is possible (and likely) that they contain different types of data.

In [62]:
# Definition of vectors
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

# Create a data frame from the vectors
planets_df <-data.frame(name,type,diameter,rotation,rings)

In [63]:
# View the dataframe
planets_df

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
5 Jupiter Gas giant          11.209      0.41   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
8 Neptune Gas giant           3.883      0.67   TRUE

In [64]:
# structure of dataframe
str(planets_df)

'data.frame':	8 obs. of  5 variables:
 $ name    : chr  "Mercury" "Venus" "Earth" "Mars" ...
 $ type    : chr  "Terrestrial planet" "Terrestrial planet" "Terrestrial planet" "Terrestrial planet" ...
 $ diameter: num  0.382 0.949 1 0.532 11.209 ...
 $ rotation: num  58.64 -243.02 1 1.03 0.41 ...
 $ rings   : logi  FALSE FALSE FALSE FALSE TRUE TRUE ...


In [65]:
# summary of dataframe
summary(planets_df)

     name               type              diameter          rotation        
 Length:8           Length:8           Min.   : 0.3820   Min.   :-243.0200  
 Class :character   Class :character   1st Qu.: 0.8448   1st Qu.:   0.1275  
 Mode  :character   Mode  :character   Median : 2.4415   Median :   0.5500  
                                       Mean   : 3.9264   Mean   : -22.6950  
                                       3rd Qu.: 5.3675   3rd Qu.:   1.0075  
                                       Max.   :11.2090   Max.   :  58.6400  
   rings        
 Mode :logical  
 FALSE:4        
 TRUE :4        
                
                
                

## 5.4: Selection of data frame elements
Similar to vectors and matrices, you select elements from a data frame with the help of square brackets `[ ]`. By using a comma, you can indicate what to select from the rows and the columns respectively. For example:

* `my_df[1,2]` selects the value at the first row and second column in my_df.
* `my_df[1:3,2:4]` selects rows 1, 2, 3 and columns 2, 3, 4 in my_df.
* Sometimes you want to select all elements of a row or column. For example, `my_df[1, ]` selects all elements of the first row. Let us now apply this technique on planets_df!

In [66]:
# The planets_df data frame from the previous exercise is pre-loaded
planets_df
# Print out diameter of of Mercury (row 1, column 3)
planets_df[1,3]

# Print out data for Mars (entire fourth row)
planets_df[4,]

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
5 Jupiter Gas giant          11.209      0.41   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
8 Neptune Gas giant           3.883      0.67   TRUE

[1] 0.382

name type               diameter rotation rings
4 Mars Terrestrial planet 0.532    1.03     FALSE

### Selection using variable name
Instead of using numerics to select elements of a data frame, you can also use the variable names to select columns of a data frame.

In [67]:
planets_df[3]

diameter
1  0.382  
2  0.949  
3  1.000  
4  0.532  
5 11.209  
6  9.449  
7  4.007  
8  3.883

In [68]:
# planets_df[,"diameter"],planets_df[,3] also works
planets_df["diameter"]

diameter
1  0.382  
2  0.949  
3  1.000  
4  0.532  
5 11.209  
6  9.449  
7  4.007  
8  3.883

### Subseting using `$` sign.
If your columns have names, you can use the $ sign:

>dataframe$colname

In [69]:
# Select the rings variable from planets_df
rings_vector <- planets_df$rings
  
# Print out rings_vector
rings_vector

[1] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE

In [70]:
# Adapt the code to select all columns for planets with rings
planets_df[rings_vector,]

name    type      diameter rotation rings
5 Jupiter Gas giant 11.209    0.41    TRUE 
6 Saturn  Gas giant  9.449    0.43    TRUE 
7 Uranus  Gas giant  4.007   -0.72    TRUE 
8 Neptune Gas giant  3.883    0.67    TRUE

### Using `subset()` function
The first argument of `subset()` specifies the data set for which you want a subset. By adding the second argument, you give R the necessary information and conditions to select the correct subset.
> subset(my_df, subset = some_condition)


In [71]:
# planets_df dataframe
planets_df

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
5 Jupiter Gas giant          11.209      0.41   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
8 Neptune Gas giant           3.883      0.67   TRUE

In [72]:
# Select planets with diameter > 4
subset(planets_df,diameter > 4)

name    type      diameter rotation rings
5 Jupiter Gas giant 11.209    0.41    TRUE 
6 Saturn  Gas giant  9.449    0.43    TRUE 
7 Uranus  Gas giant  4.007   -0.72    TRUE

In [73]:
# subset using logical column
subset(planets_df, subset = rings)

name    type      diameter rotation rings
5 Jupiter Gas giant 11.209    0.41    TRUE 
6 Saturn  Gas giant  9.449    0.43    TRUE 
7 Uranus  Gas giant  4.007   -0.72    TRUE 
8 Neptune Gas giant  3.883    0.67    TRUE

### Sorting Data frame
the `order()` function rearrange your data frame such that it starts with the smallest largest one according to your column;

In [74]:
# How order works
a <- c(1,4,6,7,9,5)
order(a)
a[order(a)]

[1] 1 2 6 3 4 5

[1] 1 4 5 6 7 9

In [75]:
# planets_df is pre-loaded in your workspace
planets_df 
# Use order() to create positions
size <- order(planets_df$diameter) 

# Use size to sort planets_df
planets_df[size,]

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
5 Jupiter Gas giant          11.209      0.41   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
8 Neptune Gas giant           3.883      0.67   TRUE

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
8 Neptune Gas giant           3.883      0.67   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
5 Jupiter Gas giant          11.209      0.41   TRUE

# 6. Working with List
A **list** in R allows you to gather a variety of objects under one name (that is, the name of the list) in an ordered way. These objects can be **matrices, vectors, data frames, even other lists**, etc. It is not even required that these objects are related to each other in any way.

## 6.1: Creating a list
To construct a list you use the function list():
> my_list <- list(comp1, comp2 ...)


In [76]:
# Vector with numerics from 1 up to 10
my_vector <- 1:10 

# Matrix with numerics from 1 up to 9
my_matrix <- matrix(1:9, ncol = 3)

# First 10 elements of the built-in data frame mtcars
my_df <- mtcars[1:10,]

# Construct list with these different elements:
my_list <- list(my_vector,my_matrix,my_df)
my_list

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

## 3.2: Creating a named list
Just like on your to-do list, you want to avoid not knowing or remembering what the components of your list stand for. That is why you should give names to them:
> my_list <- list(name1 = your_comp1, name2 = your_comp2)

This creates a list with components that are named name1, name2, and so on. If you want to **name your lists after you've created them**, you can use the `  names() ` function as you did with vectors. The following commands are fully equivalent to the assignment above:

> my_list <- list(your_comp1, your_comp2) \
> names(my_list) <- c("name1", "name2")


In [ ]:
# Vector with numerics from 1 up to 10
my_vector <- 1:10 

# Matrix with numerics from 1 up to 9
my_matrix <- matrix(1:9, ncol = 3)

# First 10 elements of the built-in data frame mtcars
my_df <- mtcars[1:10,]

# Adapt list() call to give the components names
my_list <- list(my_vector, my_matrix, my_df)
names(my_list) <- c("vector","matrix","dataframe")
# Print out my_list
my_list

### 3.3 Use of List in R


In [ ]:
city <- "Kolkata"
places <- c('New Market','Victoria Memorial','Howrah Bridge','Park Street','South Park Cemetery','Dakshineshwar Kali Temple','Belur Math','Fort William','Prinsep Ghat','Old Chinatown')

# Creating dataframe
rating <- c(4.8,5.0,4.0,3.1,3.6)
place <- c('New Market','Dakshineshwar Kali Temple','Victoria Memorial','Victoria Memorial','Howrah Bridge')
comment <- c('Nice Place', "Good Temple!!",'Must Visit','Kolkata, Attarction...','Best place near ganga!')
city_review_df <- data.frame(place,rating,comment)

# Creating R List
city_list <- list(name = city, touristPlaces = places, review = city_review_df )

In [ ]:
city_list

### 3.4 Selecting elements from a list
You can also refer to the names of the components, with `[[ ]]` or with the ` $ ` sign. Both will select the data frame representing the reviews:

In [ ]:
city_list[['name']]
city_list[['review']]

In [ ]:
city_list[[1]]
city_list[[3]]