<a href="https://colab.research.google.com/github/recervictory/LearingR/blob/main/Intermediate_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Flow Control and Loops
In this chapter, you'll learn about relational operators for comparing R objects, and logical operators like "and" and "or" for combining TRUE and FALSE values. Then, you'll use this knowledge to build conditional statements.
## Chapter Goals
- Be able to branch the flow of execution
- Be able to repeatedly execute code with loops

## 1: Conditionals and Control Flow


 **Equality**: The most basic form of comparison is equality. Used syntax `==` for comparing two string, numaric, logical values.

In [ ]:
#  Equality
# Comparison of logicals
TRUE == FALSE

# Comparison of numerics
-6 * 14 != 17 - 101

# Comparison of character strings
"useR" == "user"

# Compare a logical with a numeric
TRUE == 1

In [ ]:

# Comparison of numerics
-6 * 5 + 2 >= -10 + 1

# Comparison of character strings
"raining" <= "raining dogs"

# Comparison of logicals
TRUE > FALSE


**Greater and less than**: Apart from equality operators, Filip also introduced the less than and greater than operators: `<` and `>`. You can also add an equal sign to express less than or equal to or greater than or equal to, respectively.


In [ ]:
# Comparison of numerics
-6 * 5 + 2 >= -10 + 1

# Comparison of character strings
"raining" <= "raining dogs"

# Comparison of logicals
TRUE > FALSE

**Compare vectors**: Comparing vectors with relational operators

In [ ]:
# The linkedin and facebook vectors have already been created for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)

# Popular days
linkedin > 15
# Quiet days
linkedin <= 5

# LinkedIn more popular than Facebook
linkedin > facebook

In [4]:
# The social data has been created for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)
views <- matrix(c(linkedin, facebook), nrow = 2, byrow = TRUE)

# When does views equal 13?
views == 13
# When is views less than or equal to 14?
views <= 14
views

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7] 
[1,] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE

[,1]  [,2] [,3] [,4]  [,5] [,6]  [,7]
[1,] FALSE TRUE TRUE  TRUE TRUE FALSE TRUE
[2,] FALSE TRUE TRUE FALSE TRUE  TRUE TRUE

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 16   9    13    5   2    17   14  
[2,] 17   7     5   16   8    13   14

**Logical Operators**: There are three vectorized logical operators in R:
- ! is used for not.
- & is used for and.
- | is used for or.

In [ ]:
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
linkedin > 10 & linkedin < 15

In [ ]:
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
linkedin == 16 | linkedin == 14

In [ ]:
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
linkedin == 16 | linkedin == 14

In [ ]:
monday <-c(2,    31,    3,    61,   4,    12,    0)
tuesday <-c(21,    13,    33,    16,   43,    23,   20)
wednessday <-c(24,   18,   15,   19,   18,   22,   17)
thursday <-c(25,   25,   26,   31,   24,   36 ,  37)
names <- c("employee_1", "employee_2", "employee_3", "employee_4", "employee_5", "employee_6","employee_7")

employees <- data.frame(names,monday, tuesday, wednessday, thursday)
employees

In [ ]:
# Build a logical vector, TRUE if value in second is extreme: extremes
extremes <- employees$monday > 25 | employees$wednessday <  15
# Count the number of TRUEs in extremes
sum(extremes)

# Solve it with a one-liner
sum(employees$monday > 25 | employees$wednessday < 15)

### The if and else statement
The simplest form of flow control is conditional execution using if. if takes a logical value (more precisely, a logical vector of length one) and executes the next statement only if that value is **TRUE**.The else statement does not require a condition; its corresponding code is simply run if all of the preceding conditions in the control structure are FALSE. 
```
if (condition) {
  expr
} else if (condition) {
  expr
} else {
  expr
}
```

In [30]:
# Few simple Example
if(TRUE) message("It was true!")
if(FALSE) message("It wasn't true!")

It was true!



In [31]:
# Missing values aren’t allowed to be passed to if; doing so throws an error:
if(NA) message("Who knows if it was true?")

# Where you may have a missing value, you should test for it using is.na:
if(is.na(NA)) message("The value is missing!")

ERROR: ignored

In [ ]:
# Variables related to your last day of recordings
medium <- "LinkedIn"
num_views <- 14

# Examine the if statement for medium
if (medium == "LinkedIn") {
  print("Showing LinkedIn information")
}

# Write the if statement for num_views

if (num_views > 15) {
  print("You're popular!")
}

### else Statement Example

In [32]:
# Variables related to your last day of recordings
medium <- "LinkedIn"
num_views <- 14

# Control structure for medium
if (medium == "LinkedIn") {
  print("Showing LinkedIn information")
} else {
    print("Unknown medium")
}

# Control structure for num_views
if (num_views > 15) {
  print("You're popular!")
} else {
    print("Try to be more visible!")
}

[1] "Showing LinkedIn information"
[1] "Try to be more visible!"


In [33]:
# Variables related to your last day of recordings
medium <- "LinkedIn"
num_views <- 14

# Control structure for medium
if (medium == "LinkedIn") {
  print("Showing LinkedIn information")
} else if (medium == "Facebook") {
  # Add code to print correct string when condition is TRUE
    print("Showing Facebook information")
} else {
  print("Unknown medium")
}

# Control structure for num_views
if (num_views > 15) {
  print("You're popular!")
} else if (num_views <= 15 & num_views > 10) {
  # Add code to print correct string when condition is TRUE
 print("Your number of views is average")
} else {
  print("Try to be more visible!")
}

[1] "Showing LinkedIn information"
[1] "Your number of views is average"


### else if

In [34]:
# Variables related to your last day of recordings
medium <- "LinkedIn"
num_views <- 14

# Control structure for medium
if (medium == "LinkedIn") {
  print("Showing LinkedIn information")
} else if (medium == "Facebook") {
  # Add code to print correct string when condition is TRUE
    print("Showing Facebook information")
} else {
  print("Unknown medium")
}

# Control structure for num_views
if (num_views > 15) {
  print("You're popular!")
} else if (num_views <= 15 & num_views > 10) {
  # Add code to print correct string when condition is TRUE
 print("Your number of views is average")
} else {
  print("Try to be more visible!")
}

[1] "Showing LinkedIn information"
[1] "Your number of views is average"


In [35]:
# Variables related to your last day of recordings
li <- 15
fb <- 9

# Code the control-flow construct
if (li >= 15 & fb >= 15) {
  sms <- 2 * (li + fb)
} else if (li < 10 & fb <10) {
  sms <- 0.5 * (li + fb)
} else {
  sms <- li + fb
}

# Print the resulting sms to the console
sms

[1] 24

# 2. Loops
There are **three kinds of loops** in R: 

- while,
- for and
- repeat . 
Although vectorization means that you don’t need them as much in R as in other languages, they can still come in handy for repeatedly executing code.

### While Loop: 
The condition part of this recipe should become FALSE at some point during the execution. Otherwise, the while loop will go on indefinitely.

```
while (condition) {
  expr
}
```

In [ ]:
# Initialize the speed variable
speed <- 64

# Code the while loop
while (speed > 30 ) {
  print("Slow down!")
  speed <- speed - 7
}

# Print out the speed variable
speed

### Exercise 1:
- If the speed is greater than 48, have R print out "Slow down big time!", and decrease the speed by 11.
- Otherwise, have R simply print out "Slow down!", and decrease the speed by 6.

In [ ]:
# Initialize the speed variable
speed <- 64

# Extend/adapt the while loop
while (speed > 30) {
  print(paste("Your speed is",speed))
  if ( ) {
    ___
    ___
  } else {
    ___
    ___
  }
}

### **break statements**: break statement used to immediately break the loop
```
if (condition) {
  break
}
```
- Adapt the while loop such that it is abandoned when the speed of the vehicle is greater than 80. This time, the speed variable has been initialized to 88; keep it that way.

In [ ]:
# Initialize the speed variable
speed <- 88

while (speed > 30) {
  print(paste("Your speed is", speed))
  
  # Break the while loop when speed exceeds 80
  if ( ) {
    
  }
  
  if (speed > 48) {
    print("Slow down big time!")
    speed <- speed - 11
  } else {
    print("Slow down!")
    speed <- speed - 6
  }
}

### Loop over a vector
There are two main strategies for using `for` loop in R. 
- by element
- by index

```
primes <- c(2, 3, 5, 7, 11, 13)

# loop version 1
for (p in primes) {
  print(p)
}

# loop version 2
for (i in 1:length(primes)) {
  print(primes[i])
}
```

In [ ]:
# The linkedin vector has already been defined for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)

# Loop version 1
for(p in  linkedin) {
    print(p)
}

# Loop version 2
for(p in 1:length(linkedin)) {
    print(linkedin[p])
}

### Loop over a list
Looping over a list is just as easy and convenient as looping over a vector. 
```
primes_list <- list(2, 3, 5, 7, 11, 13)

# loop version 1
for (p in primes_list) {
  print(p)
}

# loop version 2
for (i in 1:length(primes_list)) {
  print(primes_list[[i]])
}
```
**list need double square brackets - [[ ]] - to select the list elements.**

### Loop over a matrix

In [2]:
# Creating a Matrix
a <- c(0, 1, 0)
b <- c(1, 1, 1)
c <- c(0, 1, 0)

mt <- matrix(c(a, b, c), nrow = 3, byrow = TRUE)
mt

[,1] [,2] [,3]
[1,] 0    1    0   
[2,] 1    1    1   
[3,] 0    1    0

In [3]:
# Viewing the matrix over nested loops
for (i in 1:nrow(mt)) {
  for (j in 1:ncol(mt)) {
    print(paste("On row", i, "and column", j, " contains", mt[i,j]))
  }
}

[1] "On row 1 and column 1  contains 0"
[1] "On row 1 and column 2  contains 1"
[1] "On row 1 and column 3  contains 0"
[1] "On row 2 and column 1  contains 1"
[1] "On row 2 and column 2  contains 1"
[1] "On row 2 and column 3  contains 1"
[1] "On row 3 and column 1  contains 0"
[1] "On row 3 and column 2  contains 1"
[1] "On row 3 and column 3  contains 0"
